[package]
name = "advent_of_code_2023"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.12.0"
nalgebra = "0.32.3"
pathfinding = "4.8.0"
regex = "1.10.2"
strum = "0.25.0"
strum_macros = "0.25.3"
